### ISSUE TITLE
Cropped Buttons

### ISSUE THREAD

**Issue by tswonke** [ioBroker/ioBroker.vis-lcars#2]
First of all thanks to you for your great efforts!!

I started a new LCARS-Project yesterday and came across a strange behavior:

Wenn I use a button (e. g. connected with a Homematic switch) in multiple views, it is cropped at one side when switching the views. It does not matter whether I use the same button in all views or copy it from one to another. And this occurs on all Buttons...

Is this a known issue?

I could attach images for a better explanation, or config?

**Comment by GermanBluefox** [comment]
One picture is often can explain more than 1000 words. :)
13 Июн 2016 г. 11:12 пользователь "Thomas Swonke" notifications@github.com
написал:

First of all thanks to you for your great efforts!!

I started a new LCARS-Project yesterday and came across a strange behavior:

Wenn I use a button (e. g. connected with a Homematic switch) in multiple
views, it is cropped at one side when switching the views. It does not
matter whether I use the same button in all views or copy it from one to
another. And this occurs on all Buttons...

Is this a known issue?

I could attach images for a better explanation, or config?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ioBroker/ioBroker.vis-lcars/issues/2, or mute the
thread
https://github.com/notifications/unsubscribe/AEXqgOnnXLetIMNpS3g1oF9hIeljF6yVks5qLR7zgaJpZM4I0IcH
.

**Comment by tswonke** [comment]
No problem :)

Attached you will find two screenshots (two identical views). In one of them the buttons are cropped. This was a quick first try of the vis-lcars.

![bildschirmfoto 2016-06-13 um 13 06 55](https://cloud.githubusercontent.com/assets/6401044/16008013/ef1f8a14-3175-11e6-99b2-b45ba3e8ad6d.png)
![bildschirmfoto 2016-06-13 um 13 07 08](https://cloud.githubusercontent.com/assets/6401044/16008014/f291e34a-3175-11e6-8d6d-2aab6b6b7bab.png)

**Comment by tswonke** [comment]
It seems to have something to do with the background properties of the views. Without a background all is fine. With background-color the buttons may be cropped (or overlain by something?). But I'm not able to reproduce it dependably for you to explain. It's really weird :(

**Comment by GermanBluefox** [comment]
Please send me your views as json at dogafox  at gmail.com. I promise to
handle your files as private.
14 Июн 2016 г. 0:28 пользователь "Thomas Swonke" notifications@github.com
написал:

**Comment by tswonke** [comment]
Just sent you an email with exports and screens. Thanks!

**Comment by GermanBluefox** [comment]
It is because of the page will be rendered in invisible state.
Remove flag render always and it should work.
![image](https://cloud.githubusercontent.com/assets/4582016/16045935/e84be4d2-324a-11e6-8f79-a98f475db1f3.png)

**Comment by tswonke** [comment]
Ah, thanks a lot. I will try this!

Is there any Paypal donation account for this project?

**Comment by GermanBluefox** [comment]
http://www.iobroker.net/?lang=de
Exactly in the middle :)

**Comment by tswonke** [comment]
Perfect, I used that a few days ago and already donated some money.

I thought that the lcars project might be "independent" from the donation link on the iobroker website.

**Comment by marksev1** [comment]
Tswonke do you maybe know how to set up toggle button so it toggles from true to false here in LCARS vis?

Like here: https://github.com/ioBroker/ioBroker.vis-lcars/issues/4
